export const serie_a = [
  { id: 1, nome: "Athletico-PR" },
  { id: 2, nome: "Atlético-GO" },
  { id: 3, nome: "Atlético-MG" },
  { id: 4, nome: "Bahia" },
  { id: 5, nome: "Botafogo" },
  { id: 6, nome: "RB Bragantino" },
  { id: 7, nome: "Corinthians" },
  { id: 8, nome: "Criciúma" },
  { id: 9, nome: "Cruzeiro" },
  { id: 10, nome: "Cuiabá" },
  { id: 11, nome: "Flamengo" },
  { id: 12, nome: "Fluminense" },
  { id: 13, nome: "Fortaleza" },
  { id: 14, nome: "Grêmio" },
  { id: 15, nome: "Internacional" },
  { id: 16, nome: "Juventude" },
  { id: 17, nome: "Palmeiras" },
  { id: 18, nome: "São Paulo" },
  { id: 19, nome: "Vasco" },
  { id: 20, nome: "Vitória" },
];
