export const serie_b = [
  { id: 1, nome: "Amazonas" },
  { id: 2, nome: "América-MG" },
  { id: 3, nome: "Avaí" },
  { id: 4, nome: "Botafogo-SP" },
  { id: 5, nome: "Brusque" },
  { id: 6, nome: "CRB" },
  { id: 7, nome: "Ceará" },
  { id: 8, nome: "Chapecoense" },
  { id: 9, nome: "Coritiba" },
  { id: 10, nome: "Goiás" },
  { id: 11, nome: "Guarani" },
  { id: 12, nome: "Ituano" },
  { id: 13, nome: "Mirassol" },
  { id: 14, nome: "Novorizontino" },
  { id: 15, nome: "Operário-PR" },
  { id: 16, nome: "Paysandu" },
  { id: 17, nome: "Ponte Preta" },
  { id: 18, nome: "Santos" },
  { id: 19, nome: "Sport" },
  { id: 20, nome: "Vila Nova" },
];
