// Primeiro Turno
export const primeiro_turno_bragantino = [
  {
    id: 1,
    adversario: "Fluminense",
    mandoDeCampo: "Fora",
    local: "Maracanã, RJ",
  },
  {
    id: 2,
    adversario: "Vasco",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 3,
    adversario: "Corinthians",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 4,
    adversario: "Fortaleza",
    mandoDeCampo: "Fora",
    local: "Castelão, CE",
  },
  {
    id: 5,
    adversario: "Flamengo",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 6,
    adversario: "Bahia",
    mandoDeCampo: "Fora",
    local: "Arena Fonte Nova, BA",
  },
  {
    id: 7,
    adversario: "Grêmio",
    mandoDeCampo: "Fora",
    local: "Arena do Grêmio, RS",
  },
  {
    id: 8,
    adversario: "Atlético-MG",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 9,
    adversario: "Juventude",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 10,
    adversario: "Palmeiras",
    mandoDeCampo: "Fora",
    local: "Allianz Parque, SP",
  },
  {
    id: 11,
    adversario: "Vitória",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 12,
    adversario: "Botafogo",
    mandoDeCampo: "Fora",
    local: "Nilton Santos, RJ",
  },
  {
    id: 13,
    adversario: "Cuiabá",
    mandoDeCampo: "Fora",
    local: "Arena Pantana, MT",
  },
  {
    id: 14,
    adversario: "Atlético-GO",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 15,
    adversario: "São Paulo",
    mandoDeCampo: "Fora",
    local: "Morumbi, SP",
  },
  {
    id: 16,
    adversario: "Internacional",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 17,
    adversario: "Cruzeiro",
    mandoDeCampo: "Fora",
    local: "Mineirão, MG",
  },
  {
    id: 18,
    adversario: "Athletico-PR",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 19,
    adversario: "Criciúma",
    mandoDeCampo: "Fora",
    local: "Heriberto Hülse, SC",
  },
];

// Segundo Turno
export const segundo_turno_bragantino = [
  {
    id: 20,
    adversario: "Fluminense",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 21,
    adversario: "Vasco",
    mandoDeCampo: "Fora",
    local: "São Januário, RJ",
  },
  {
    id: 22,
    adversario: "Corinthians",
    mandoDeCampo: "Fora",
    local: "Neo Química Arena, SP",
  },
  {
    id: 23,
    adversario: "Fortaleza",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 24,
    adversario: "Flamengo",
    mandoDeCampo: "Fora",
    local: "Maracanã, RJ",
  },
  {
    id: 25,
    adversario: "Bahia",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 26,
    adversario: "Grêmio",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 27,
    adversario: "Atlético-MG",
    mandoDeCampo: "Fora",
    local: "Arena MRV, MG",
  },
  {
    id: 28,
    adversario: "Juventude",
    mandoDeCampo: "Fora",
    local: "Alfredo Jaconi,  RS",
  },
  {
    id: 29,
    adversario: "Palmeiras",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 30,
    adversario: "Vitória",
    mandoDeCampo: "Fora",
    local: "Barradão, BA",
  },
  {
    id: 31,
    adversario: "Botafogo",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 32,
    adversario: "Cuiabá",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 33,
    adversario: "Atlético-GO",
    mandoDeCampo: "Fora",
    local: "Antônio Accioly, GO",
  },
  {
    id: 34,
    adversario: "São Paulo",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 35,
    adversario: "Internacional",
    mandoDeCampo: "Fora",
    local: "Beira-Rio, RS",
  },
  {
    id: 36,
    adversario: "Cruzeiro",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 37,
    adversario: "Athletico-PR",
    mandoDeCampo: "Fora",
    local: "Arena da Baixada, PR",
  },
  {
    id: 38,
    adversario: "Criciúma",
    mandoDeCampo: "Casa",
    local: "Nabi Abi Chedid, SP",
  },
];
