export const primeiro_turno_flamengo = [
  {
    id: 1,
    adversario: "Fluminense",
    mandoDeCampo: "Fora",
    local: "Maracanã, RJ",
  },
  {
    id: 2,
    adversario: "Gremio",
    mandoDeCampo: "Casa",
    local: "São Januario, RJ",
  },
  {
    id: 3,
    adversario: "Corinthians",
    mandoDeCampo: "Fora",
    local: "Arena Corinthians, SP",
  },
  {
    id: 4,
    adversario: "Bahia",
    mandoDeCampo: "Casa",
    local: "São Januario, RJ",
  },
  {
    id: 5,
    adversario: "São Paulo",
    mandoDeCampo: "Fora",
    local: "Morumbi, SP",
  },
  {
    id: 6,
    adversario: "Palmeiras",
    mandoDeCampo: "Fora",
    local: "Allianz Parque, SP",
  },
  {
    id: 7,
    adversario: "Botafogo",
    mandoDeCampo: "Fora",
    local: "Nilton Santos, RJ",
  },
  {
    id: 8,
    adversario: "Ceará",
    mandoDeCampo: "Casa",
    local: "São Januario, RJ",
  },
  {
    id: 9,
    adversario: "Internacional",
    mandoDeCampo: "Fora",
    local: "Beira Rio, RS",
  },
  {
    id: 10,
    adversario: "Sport",
    mandoDeCampo: "Casa",
    local: "São Januario, RJ",
  },
  {
    id: 11,
    adversario: "Fortaleza",
    mandoDeCampo: "Fora",
    local: "Castelão, CE",
  },
  {
    id: 12,
    adversario: "Athletico",
    mandoDeCampo: "Casa",
    local: "São Januario, RJ",
  },
  {
    id: 13,
    adversario: "Cuiabá",
    mandoDeCampo: "Fora",
    local: "Arena Pantanal, MT",
  },
  {
    id: 14,
    adversario: "Juventude",
    mandoDeCampo: "Casa",
    local: "São Januario, RJ",
  },
  {
    id: 15,
    adversario: "Flamengo",
    mandoDeCampo: "Fora",
    local: "Maracanã, RJ",
  },
];
