export const primeiro_turno_vasco = [
  {
    id: 1,
    adversario: "Grêmio",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 2,
    adversario: "RB Bragantino",
    mandoDeCampo: "Fora",
    local: "Nabi Abi Chedid, SP",
  },
  {
    id: 3,
    adversario: "Fluminense",
    mandoDeCampo: "Fora",
    local: "Maracanã, RJ",
  },
  {
    id: 4,
    adversario: "Criciúma",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 5,
    adversario: "Athletico-PR",
    mandoDeCampo: "Fora",
    local: "Arena da Baixada, PR",
  },
  {
    id: 6,
    adversario: "Vitória",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 7,
    adversario: "Flamengo",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 8,
    adversario: "Palmeiras",
    mandoDeCampo: "Fora",
    local: "Allianz Parque, SP",
  },
  {
    id: 9,
    adversario: "Cruzeiro",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 10,
    adversario: "Juventude",
    mandoDeCampo: "Fora",
    local: "Alfredo Jaconi,  RS",
  },
  {
    id: 11,
    adversario: "São Paulo",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 12,
    adversario: "Bahia",
    mandoDeCampo: "Fora",
    local: "Arena Fonte Nova, BA",
  },
  {
    id: 13,
    adversario: "Botafogo",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 14,
    adversario: "Fortaleza",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 15,
    adversario: "Internacional",
    mandoDeCampo: "Fora",
    local: "Beira-Rio, RS",
  },
  {
    id: 16,
    adversario: "Corinthians",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 17,
    adversario: "Atlético-GO",
    mandoDeCampo: "Fora",
    local: "Antônio Accioly, GO",
  },
  {
    id: 18,
    adversario: "Atlético-MG",
    mandoDeCampo: "Fora",
    local: "Arena MRV, MG",
  },
  {
    id: 19,
    adversario: "Cuiabá",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
];

export const segundo_turno_vasco = [
  {
    id: 1,
    adversario: "Grêmio",
    mandoDeCampo: "Fora",
    local: "Arena do Grêmio, RS",
  },
  {
    id: 2,
    adversario: "RB Bragantino",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 3,
    adversario: "Fluminense",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 4,
    adversario: "Criciúma",
    mandoDeCampo: "Fora",
    local: "Heriberto Hülse, SC",
  },
  {
    id: 5,
    adversario: "Athletico-PR",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 6,
    adversario: "Vitória",
    mandoDeCampo: "Fora",
    local: "Barradão, BA",
  },
  {
    id: 7,
    adversario: "Flamengo",
    mandoDeCampo: "Fora",
    local: "Maracanã, RJ",
  },
  {
    id: 8,
    adversario: "Palmeiras",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 9,
    adversario: "Cruzeiro",
    mandoDeCampo: "Fora",
    local: "Mineirão, MG",
  },
  {
    id: 10,
    adversario: "Juventude",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 11,
    adversario: "São Paulo",
    mandoDeCampo: "Fora",
    local: "Morumbi, SP",
  },
  {
    id: 12,
    adversario: "Bahia",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 13,
    adversario: "Botafogo",
    mandoDeCampo: "Fora",
    local: "Nilton Santos, RJ",
  },
  {
    id: 14,
    adversario: "Fortaleza",
    mandoDeCampo: "Fora",
    local: "Castelão, CE",
  },
  {
    id: 15,
    adversario: "Internacional",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 16,
    adversario: "Corinthians",
    mandoDeCampo: "Fora",
    local: "Arena Corinthians, SP",
  },
  {
    id: 17,
    adversario: "Atlético-GO",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 18,
    adversario: "Atlético-MG",
    mandoDeCampo: "Casa",
    local: "São Januário, RJ",
  },
  {
    id: 19,
    adversario: "Cuiabá",
    mandoDeCampo: "Fora",
    local: "Arena Pantanal, MT",
  },
];
